image: knksknsy/docker-nrf5

sdk-test:
  script:
    - cd ${CI_PROJECT_DIR}/tests
    - chmod +x sdk-test.sh
    - ./sdk-test.sh

build-test:   
  script:
    - cd ${CI_PROJECT_DIR}/fruitymesh
    - make ENV=docker
  only:
    - master
    - dev
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_ID}"
    when: always
    expire_in: 7d
    paths:
      - "${CI_PROJECT_DIR}/fruitymesh/_build/smart_penguins.bin"
